
###################################
# Docker Compose
###################################
version: '3'
services:
  rest980:
    container_name: rest980
    image: akkaish/rest980:latest
    ports:
      - "3000:3000"
    environment:
      #Set these in the .env file
      - BLID
      - PASSWORD
      - ROBOT_IP
      - FIRMWARE_VERSION
    restart: unless-stopped
    build: .
  php-nginx:
    container_name: php-nginx
    image: webhippie/php-nginx:latest
    environment:
      NGINX_WEBROOT: "/app"
    volumes:
      - /<HA CONFIG PATH>/vacuum:/app
    ports:
      - "3001:8080"
    restart: unless-stopped